---
name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build and Test
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          set-safe-directory: false
        
      - name: Setup Java (if applicable)
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: temurin
          
      - name: Install Dependencies
        run: |
          C:\Users\Mohammed\Downloads\apache-maven-3.9.9-bin\apache-maven-3.9.9\bin\mvn clean install
          
  deploy:
    name: Deploy with Ansible
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          set-safe-directory: false
          
      - name: Configure SSH
        run: >
          New-Item -ItemType Directory -Path $HOME\.ssh -Force
          "${{ secrets.SSH_PRIVATE_KEY }}" | Out-File -Append -FilePath ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.yml deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
