name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Print Hello World
      - name: Print Hello World
        run: echo "Hello World from GitHub Actions!"
